#define VER_MAJOR 1
#define VER_MINOR 2
#define VER_BUILD 54
#define VER_ALLSTR "1.2 build 54 release"
#define COPYRIGHT "Copyright © 2000-2004, ZG"

#define PLUG_DISPLAYNAME "Background copy Plugin for FAR Manager 1.7+."
#define PLUG_INTERNELNAME "bcopy.dll"

#define SVC_INTERNELNAME "bcsvc.exe"
#define SVC_DISPLAYNAMEA "FAR Background Copy Service"
#define SVC_DISPLAYNAMEW L"FAR Background Copy Service"
#define VERSION SVC_DISPLAYNAMEA". Version "VER_ALLSTR", 01.04.2004.\n"
