[English]
0=Rename files

1=File mas&k:
2=Sear&ch in selected
3=Search with file-&mask
4=Searc&h in folders:
5=&Process subfolders
6=More opt&ions...
7=Configur&e
8="Target: "

9=Search &for
10=&Replace with
11=Case sensiti&ve

12=NewName: "Your FAR is too old :("

13=I&nitiate value of the counter by zero in each directory
14=Write l&og-file

15=OK
16=Cancel

17=Warning
18=Configuration
19=Incorrect regular expressions in search string!
20=Incorrect regular expressions in replace string

21=Scheme

22="Searching in: "

23=Confirma&tion for renaming

24=Rename
25=&Scheme
26=Save

30=&History of S&R
31=&Another history
32=Search &for
33=&Replace with

34=Folder is read only
35=File already exists
36=Do you like to overwrite it?

40=Confirmation of the renaming
41=&Old name:
42=&New name:
43=&Do not show this dialog again

50=NewName: Options
51=History
52=Log
53=Template: &Log-filename
54=Template: &Successful renaming
55=Template: &Unsuccessful renaming

60=Incorrect regular expressions log-filename template
61=Incorrect regexps "successful renaming" template
62=Incorrect regexps "unsuccessful renaming" template

70=Search files
71=Search folders
72=Search files and folders

rxe02=Syntax error.
rxe03=Unbalanced brackets.
rxe04=Max recursive brackets level reached.
rxe05=Invalid options combination.
rxe06=Reference to nonexistent bracket.
rxe07=Invalid escape char.
rxe08=Invalid range value.
rxe09=Quantifier applyed to invalid object.
rxe10=Max brackets number reached.
rxe11=You cannot use named bracket in this expression.
rxe12=Reference to undefined named bracket.
rxe13=When looking backward, expression is to be of a fixed length.

[Russian]
0=Переименование файлов

1=Маска &файлов:
2=Искать &в отмеченном
3=Искать по мас&ке
4=Искать в ка&талогах:
5=Обрабатывать &подкаталоги
6=Дополните&льно
7=Настро&йка
8="Цель: "

9=&Искать
10=&Заменить на
11=&Учитывать регистр

12=NewName: "Не могу работать с этой версией FAR"

13=Обнулять сч&етчик в каждом каталоге
14=Писать ло&г-файл

15=ОК
16=Отмена

17=Внимание
18=Настройка
19=Некорректные регулярные выражения в строке поиска!
20=Некорректные регулярные выражения в строке замены

21=Схема

22="Поиск в: "

23=По&дтверждение переименования

24=Переи&меновать
25=Схе&ма
26=С&охранить

30=И&стория S&R
31=&Другая история
32=&Искать
33=&Заменить на

34=Каталог имеет атрибут "Только для чтения"
35=Файл с таким именем уже существует
36=Вы хотите перезаписать его?

40=Подтверждение переименования
41=&Старое имя:
42=&Новое имя:
43=Не &показывать этот диалог снова

50=NewName: Настройки
51=История
52=Лог
53=Шаблон: и&мя лог-файла
54=Шаблон: &удачное переименование
55=Шаблон: неудачное &переименование

60=Некорректные регулярные выражения в шаблоне имени лог-файла
61=Некорректные регэкспы в шаблоне "удачное переименование"
62=Некорректные регэкспы в шаблоне "неудачное переименование"

70=Искать файлы
71=Искать каталоги
72=Искать файлы и каталоги

rxe02=Синтаксическая ошибка.
rxe03=Нарушен баланс скобок.
rxe04=Превышено допустимое количество вложенных скобок.
rxe05=Неправильная комбинация опций.
rxe06=Ссылка на несуществующую скобку.
rxe07=Неправильный спецсимвол.
rxe08=Неправильное значение диапазона.
rxe09=Ошибка использования квантификатора.
rxe10=Слишком много скобок, на которые можно ссылаться по номерам.
rxe11=В данном регэкспе нельзя использовать поименованные скобки.
rxe12=Ссылка на несуществующую поименованную скобку.
rxe13=При просмотре назад выражение должно быть фиксированной длины.

[Ukrainian]
0=Перейменування файлiв

1=Маска &файлiв:
2=Шукати у &вiдмiченому
3=Шу&кати по масцi
4=Шукати в ка&талогах:
5=Обробляти &пiдкаталоги
6=Дода&тково
7=Настро&йка
8="Цiль: "

9=&Шукати
10=&Замiнити на
11=&Враховувати регiстр

12=NewName: "Не можу працювати з цiєю версiєю FAR"

13=Обнуляти лi&чильник в кожному каталозi
14=Записувати ло&г-файл

15=ОК
16=Скасувати

17=Увага
18=Настройка
19=Некоректнi регулярнi вирази в рядку пошуку!
20=Некоректнi регулярнi вирази в рядку замiни

21=Схема

22="Пошук в: "

23=Пi&дтвердження переiменування

24=Переi&менувати
25=Схе&ма
26=Зберегти

30=I&сторiя S&R
31=&Iнша iсторiя
32=&Шукати
33=&Замiнити на

34=Каталог має атрибут "Тiльки для читання"
35=Файл з таким iменем вже iснує
36=Ви хочете перезаписати його?

40=Пiдтвердження перейменування
41=&Старе iм'я:
42=&Нове iм'я:
43=Не &показувати цей дiалог знову

50=NewName: Настройки
51=Iсторiя
52=Лог
53=Шаблон: i&м'я лог-файла
54=Шаблон: &вдале переiменування
55=Шаблон: невдале &переiменування

60=Некоректнi регулярнi вирази в шаблонi iменi лог-файла
61=Некоректнi регекспи в шаблонi "вдале перейменування"
62=Некоректнi регекспи в шаблонi "невдале перейменування"

70=Шукати файли
71=Шукати каталоги
72=Шукати файли та каталоги

rxe02=Синтаксична помилка.
rxe03=Порушений баланс дужок.
rxe04=Перевищено допустиму кiлькiсть вкладених дужок.
rxe05=Неправильна комбiнацiя опцiй.
rxe06=Посилання на неiснуючу дужку.
rxe07=Неправильний спецсимвол.
rxe08=Неправильне значення дiапазону.
rxe09=Помилка використання квантифiкатора.
rxe10=Забагато дужок, на якi можна посилатися по номерам.
rxe11=В даному регекспi не можна використовувати iменованi дужки.
rxe12=Посилання на неiснуючу iменовану дужку.
rxe13=При реверсивному переглядi повинний бути вираз фiксованої довжини
