ADC Plugin for FAR (product number 1170-10): order form
=======================================================

Mail this form to:	Universal Commerce, Inc.
			ATTN: Orders
			PO Box 1816
			Issaquah, WA 98029
			United States of America

Or fax it to:		1 888 353-7276 (U.S. and Canada; toll-free)
			1 425 392-0223 (other countries; regular)

Or just call: 		1 877 353-7297 (U.S. and Canada; toll-free)
			1 425 392-2294 (other countries; regular)


Check, money order or credit card order accepted
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Note: for mailed orders, the checks need to be made out to Universal
Commerce Inc. The product ID (1170-1) should be mentioned on the
"memo" of the check. Checks and money orders should be drawn in US
Funds. A purchase order must be faxed or mailed to the address listed
above with all necessary information including billing information.

Order Information
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ADC Plugin for FAR (1170-10)             Price/Unit   Quantity   Total
----------------------------------------------------------------------

Program license                              $10.00     ______   _____
Mail or fax order                             $2.50              _____

TOTAL AMOUNT ($U.S.)			      	    	    __________

Note: if you place an order by fax (with credit card), or pay with
check, money order or purchase order, please include additional
$2.50 (see above). Otherwise, your order will not be processed. If you
place an order by phone, you'll be charged for additional $3. For
online orders, there are no additional charges.

Payment Information
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
First Name:      _____________________________________________________

Last Name:       _____________________________________________________

Company:         _____________________________________________________

Street Address:  _____________________________________________________

                 _____________________________________________________

City: 		 _____________________________________________________

State/Province:  _____________________________________________________

Zip/Postal Code: _____________________________________________________

Country:         _____________________________________________________

Daytime Phone:   _____________________________________________________

Fax:             _____________________________________________________

Email Address:   _____________________________________________________

Payment:         __ MasterCard     __ VISA     __ AMEX     __ Discover
                 __ Check       __ Money order       __ Purchase order


For credit card orders:

Name on Card: ________________________________________________________

Credit Card Number: __________________________________________________  

Expiration Date: month _______________ year (4 digits) _______________


                Signature : ____________________  Date: ______________
