[English]
0=Search options
1=Replacement options
2=History options
3=Other options

4=&Show message if nothing was found
5=R&eplace $ with \r\n when searching with regexps
6=Wor&k without // when searching with regexps
7=Show men&u
8=Only &create log
9=&Temporary panel
10=&Log filename suffix
11=Word consists of characters and &digits
12=&Additional symbols of words:
13=Search from &next position in editor and viewer
14=Do not process overlapping occurrences...
15=...during &replacement and counting
16=...&when continuing searching

17=&Reset counter for each file
18=&Delete empty lines

19=Ow&n history
20=System h&istory
21=&Another history

22=Show f&ile name in console title
23=Remo&ve selection from files
24=Process &selected text if selected area exist
25=Search &without regular expressions by default
26=Save time of the last change
27=Show found in editor
28=Smart
29=At the top of the screen
30=In the middle of the screen
31=At the bottom of the screen

32=Ok
33=Cancel

34=Search &for
35=&Replace with
36=Search with file-&mask
37=Searc&h in folders

38=Configure Search And Replace

39=Path for settings storage:

40=Use string from a history if there is no word under the cursor

41=Temporary panel
42=&Add to Disks menu
43="Disks menu &hotkey ('1'-'9'). Leave empty to autoassign"
44=Column &types
45=Column &widths
46=Status line column types
47=Status line column widths
48=&Fullscreen view

49=Store found occurrences in cache (in editor)

50=Process selected items if panel contains selected items
51=Show message if work is interrupted by &ESC

52=Save replace data to file

53=&Put found files list in empty panel

54=Messages options
55=Show &final message

56=Change top screen line if found string exists in current screen

57=Empty search and replace string at first

58=&Select found in editor
59=Pick up the word in editor

60=Path for plugins:

61=File-type settings

70=Open search dialog in the locked editor

80=Process OPEN_FINDLIST command

[Russian]
0=Настройки Поиска
1=Настройки Замены
2=Настройки Истории
3=Прочие настройки

4=&Сообщение о том, что ничего не нашли
5=З&аменять при поиске с регэкспами $ на \r\n
6=&Работа без // при поиске с регэкспами
7=&Показывать меню
8=То&лько записать лог
9=&Временная панель
10=Окон&чание имени лога
11=Слово состоит из букв и &цифр
12=&Дополнительные знаки слов:
13=&Искать со следующей позиции в редакторе и вьюере
14=Не обрабатывать перекрывающиеся вхождения...
15=...при заме&не и подсчете
16=...при продолж&ении поиска

17=Сб&расывать счетчик для каждого файла
18=&Удалять пустую строку

19=С&воя история
20=Систе&мная история
21=&Другая история

22=Показ&ывать имя файла в заголовке консоли
23=&Удалить выделение с файлов
24=Работа в &выделенном тексте, если есть выделенная область
25=Поиск без &регулярных выражений по умолчанию
26=Сохран&ять время последнего изменения
27=Показывать найденное в редакторе...
28=Ре&шать на лету
29=В верхней части экр&ана
30=В &центре
31=В н&ижней части экрана

32=ОК
33=Отмена

34=&Искать
35=&Заменить на
36=Искать по мас&ке
37=Искать в ка&талогах

38=Поиск и Замена: Настройка

39=Пут&ь для хранения настроек:

40=Испол&ьзовать строку из истории, если под курсором нет слова

41=Временная панель
42=&Добавить к меню дисков
43="&Клавиша доступа ('1'-'9'). Если не введена, назначается сама"
44=&Типы колонок
45=&Ширина колонок
46=Типы колонок &строки статуса
47=Ш&ирина колонок строки статуса
48=&Полноэкранный режим

49=Кэ&шировать список найденного в редакторе

50=И&скать в отмеченном, если есть отмеченные элементы на панели
51=&Показывать сообщение о том, что работа прервана по ESC

52=Сохранить замену в файл

53=&Результат поиска помещать на пустую панель

54=Настройки Сообщений
55=Показывать &финальное сообщение

56=Менять верхнюю строчку, если найденное есть на экране

57=При первом запуске строка поиска и замены должна быть пустой

58=В&ыделять найденное в редакторе
59=Подхватывать слово в редакторе

60=Путь для плагинов:

61=Настройки типов файлов

70=Открывать диалог поиска в редакторе с запретом модификации

80=Обрабатывать команду OPEN_FINDLIST

[Ukrainian]
0=Настройки Пошуку
1=Настройки Замiни
2=Настройки Iсторiї
3=Iншi настройки

4=&Повiдомлення про те, що нiчого не знайшли
5=З&амiняти при пошуку з регекспами $ на \r\n
6=&Робота без // при пошуку з регекспами
7=Показувати &меню
8=Тiльки записати &лог
9=&Тимчасова панель
10=Закiн&чення iменi лога
11=&Слово мiстить букви та цифри
12=&Додатковi символи для слiв:
13=&Шукати з наступної позицiї в редакторi та в'юерi
14=&Не обробляти входження, що перекриваються...
15=...при замi&нi та пiдрахунку
16=...при продовж&еннi пошуку

17=&Скидати лiчильник для кожного файлу
18=&Видаляти пустий рядок

19=С&воя iсторiя
20=Систе&мна iсторiя
21=&Iнша iсторiя

22=&Показувати iм'я файла в заголовку консолi
23=&Зняти вiдмiтку з файлiв
24=&Робота у видiленому текстi, якщо є видiлена область
25=Пошук без &регулярних виразiв по замовчанню
26=Зберiгати час останньої модифiкацiї
27=Показувати знайдене в редакторi...
28=Вирiшувати на льоту
29=В верхнiй частинi екрану
30=В центрi
31=В нижнiй частинi екрану

32=&ОК
33=&Скасувати

34=&Шукати
35=&Замiнити на
36=Шукати по &масцi
37=Шукати у ка&талогах

38=Пошук та Замiна: Настройка

39=Каталог для зберiгання настройок:

40=Використовувати рядок з iсторiї, якщо пiд курсором нема слова

41=Тимчасова панель
42=&Добавити в меню дискiв
43="&Клавiша доступу ('1'-'9'). Якщо не введена, призначається сама"
44=&Типи колонок
45=&Ширина колонок
46=Типи колонок в рядку статуса
47=Ш&ирина колонок в рядку статуса
48=&Повноекранний режим

49=Кеширувати список знайденого в редакторi

50=Шукати у вiдмiченому, якщо є вiдмiченi елементи на панелi
51=&Показувати повiдомлення про те, що роботу перервано по ESC

52=Зберегти замiну в файл

53=&Результат пошуку помiщати на пусту панель

54=Настройки Повiдомлень
55=Показувати &фiнальне повiдомлення

56=Мiняти верхнiй рядок, якщо знайдене є на екранi

57=При першому запуску рядок пошуку та замiни має бути пустим

58=Вiдмiчати знайдене в редакторi
59=Пiдхоплювати слово в редакторi

60=Каталог для плагiнiв:

61=Настройки типiв файлiв

70=Вiдкривати дiалог пошуку в редакторi iз забороною модифiкацiї

80=Обробляти команду OPEN_FINDLIST
