[English]
0=Version Info

1=VerInfo: "Your FAR is too old :("
2=

3=OK

4=There is no VersionInfo in this object
5=Cannot open the file

10="Selected object   : "
11="CompanyName       : "
12="FileDescription   : "
13="FileVersion       : "
14="InternalName      : "
15="LegalCopyright    : "
16="OriginalFilename  : "
17="ProductName       : "
18="ProductVersion    : "
19="Comments          : "
20="LegalTrademarks   : "
21="Language          : "
22="FileType          : "
23="FileOS            : "
24="FileFlags         : "

25="&Copy to clipboard"

26=Warning

[Russian]
0=Информация о версии файла

1=VerInfo: "Не могу работать с этой версией FAR"
2=

3=ОК

4=Этот объект не содержит информации о версии
5=Не удалось открыть файл

10="Исследуемый объект: "
11="Производитель     : "
12="Описание          : "
13="Версия файла      : "
14="Внутреннее имя    : "
15="Авторские права   : "
16="Исходное имя файла: "
17="Имя продукта      : "
18="Версия продукта   : "
19="Заметки           : "
20="Товарные знаки    : "
21="Язык              : "
22="Тип файла         : "
23="ОС                : "
24="Дополнит. сведения: "

25="&Скопировать в буфер обмена"

26=Внимание

[Ukrainian]
0=Iнформацiя про версiю файлу

1=VerInfo: "Не можу працювати з цiєю версiєю FAR"
2=

3=ОК

4=Цей об'єкт не мiстить iнформацiї про версiю
5=Не можу вiдкрити файл

10="Дослiджуваний об'єкт: "
11="Виробник            : "
12="Опис                : "
13="Версiя файлу        : "
14="Внутрiшнє iм'я      : "
15="Авторськi права     : "
16="Первiсне iм'я файлу : "
17="Iм'я продукту       : "
18="Версiя продукту     : "
19="Нотатки             : "
20="Товарнi знаки       : "
21="Мова                : "
22="Тип файлу           : "
23="FileOS              : "
24="FileFlags           : "

25="&Зробити копiю в буфер обмiну"

26="Увага"
