.SUFFIXES: .cc .cpp .c .o

TARGET=../bin/vins.dll
DOCTARGET=../file_id.diz ../bin/vins.lng
DEF=vins.def
OBJS=../o/vins.o ../o/vins.res.o
LIBS=-lcrtdll

all: $(TARGET) $(DOCTARGET)

WFLAGS=-ffor-scope -Wall -W -Werror -Wno-unused -Wpointer-arith -Wcast-qual -Wconversion
CFLAGS=-c -mcpu=pentiumpro -Os $(WFLAGS) -fno-rtti -fno-exceptions -fomit-frame-pointer -fstrict-aliasing
LFLAGS=-mdll -s -nostartfiles

RM=rm -f
CC=gcc
DLLTOOL=dlltool
MAKE=make
M4=m4
WINDRES=windres
CP=cp

$(TARGET): $(OBJS)
	$(CC) $(LFLAGS) -o nul -Xlinker --base-file -Xlinker $(TARGET).base $(OBJS) $(LIBS)
	$(DLLTOOL) --dllname $(TARGET) --base-file $(TARGET).base --output-exp $(TARGET).exp --def $(DEF)
	$(CC) $(LFLAGS) -o $@ $(OBJS) $(TARGET).exp $(LIBS)
	$(RM) $(TARGET).base
	$(RM) $(TARGET).exp

../o/%.o: %.cpp
	$(CC) $(CFLAGS) -o $@ $<

../o/vins.res.o: vins.rc ./bootstrap/vinsversion.h
	windres -i $< -o $@

./bootstrap/vinsversion.h: vinsversion.m4 vins_ver.m4
	$(M4) $< > $@

../file_id.diz: file_id_diz.m4 vins_ver.m4
	$(M4) $< > $@

../bin/vins.lng: vins.lng
	$(CP) $< $@
