[English]
0=File list creator

1=File mas&k:
2=Sear&ch in selected
3=Search with file-&mask
4=Searc&h in folders:
5=&Process subfolders
6=More opt&ions...
7=Configur&e
8="Target: "

9=Enter name of file &to create:
10=First line
11=Last line

12=Dir2File: "Your FAR is too old :("
13=

14=I&nitiate value of the counter by zero in each directory
15=Configuration

16=OK
17=Cancel

18=Warning

19=C&ode page of the output file:

20=Incorrect regular expressions in search string!
21=Incorrect regular expressions in replace string

22=Scheme

23="Searching in: "

24=Rename
25=&Scheme
26=Save

27=Common counter
28=

29=Directory

30=Type (file-mask)
31=Search Template
32=Replace template

33=File already exists
34=Do you wish to overwrite it?

70=Search files
71=Search folders
72=Search files and folders

rxe02=Syntax error.
rxe03=Unbalanced brackets.
rxe04=Max recursive brackets level reached.
rxe05=Invalid options combination.
rxe06=Reference to nonexistent bracket.
rxe07=Invalid escape char.
rxe08=Invalid range value.
rxe09=Quantifier applyed to invalid object.
rxe10=Max brackets number reached.
rxe11=You cannot use named bracket in this expression.
rxe12=Reference to undefined named bracket.
rxe13=When looking backward, expression is to be of a fixed length.
 
[Russian]
0=Создатель списка файлов

1=Маска &файлов:
2=Искать &в отмеченном
3=Искать по мас&ке
4=Искать в ка&талогах:
5=Обрабатывать &подкаталоги
6=Дополните&льно
7=Настро&йка
8="Цель: "

9=Введите &имя создаваемого файла:
10=Пе&рвая строка
11=Последня&я строка

12=Dir2File: "Не могу работать с этой версией FAR"
13=

14=Обнулять сч&етчик в каждом каталоге
15=Настройка

16=ОК
17=Отмена

18=Внимание

19=Ко&дировка создаваемого файла:

20=Некорректные регулярные выражения в строке поиска!
21=Некорректные регулярные выражения в строке замены

22=Схема

23="Поиск в: "

24=Переи&меновать
25=Схе&ма
26=С&охранить

27=Об&щий счетчик
28=

29=Каталог

30=Тип (маска вклю&чения)
31=&Шаблон для поиска
32=Шаблон для &записи

33=Файл с таким именем уже существует
34=Вы хотите перезаписать его?

70=Искать файлы
71=Искать каталоги
72=Искать файлы и каталоги

rxe02=Синтаксическая ошибка.
rxe03=Нарушен баланс скобок.
rxe04=Превышено допустимое количество вложенных скобок.
rxe05=Неправильная комбинация опций.
rxe06=Ссылка на несуществующую скобку.
rxe07=Неправильный спецсимвол.
rxe08=Неправильное значение диапазона.
rxe09=Ошибка использования квантификатора.
rxe10=Слишком много скобок, на которые можно ссылаться по номерам.
rxe11=В данном регэкспе нельзя использовать поименованные скобки.
rxe12=Ссылка на несуществующую поименованную скобку.
rxe13=При просмотре назад выражение должно быть фиксированной длины.

[Ukrainian]
0=Створювач списку файлiв

1=Маска &файлiв:
2=Шукати у &вiдмiченому
3=Шукати по мас&цi
4=Шукати в ка&талогах:
5=Обробляти &пiдкаталоги
6=До&датково
7=Наст&ройка
8="Цiль: "

9=Введiть i&м'я файла, що створюється:
10=Перший рядок
11=Останнiй рядок

12=Dir2File: "Не можу працювати з цiєю версiєю FAR"
13=

14=Обнуляти лi&чильник в кожному каталозi
15=Настройка

16=ОК
17=Вiдмiна

18=Увага

19=Ко&дування файла, що створюється:

20=Некоректнi регулярнi вирази в рядку пошуку!
21=Некоректнi регулярнi вирази в рядку замiни

22=Схема

23="Пошук в: "

24=Перей&менувати
25=Схе&ма
26=Зберегти

27=Загальний лiчильник
28=

29=Каталог

30=Тип (маска включення)
31=&Шаблон для пошуку
32=Шаблон для &запису

33=Файл з таким iменем вже iснує
34=Ви бажаєте перезаписати його?

70=Шукати файли
71=Шукати каталоги
72=Шукати файли та каталоги

rxe02=Синтаксична помилка.
rxe03=Порушений баланс дужок.
rxe04=Перевищено допустиму кiлькiсть вкладених дужок.
rxe05=Неправильна комбiнацiя опцiй.
rxe06=Посилання на неiснуючу дужку.
rxe07=Неправильний спецсимвол.
rxe08=Неправильне значення дiапазону.
rxe09=Помилка використання квантифiкатора.
rxe10=Забагато дужок, на якi можна посилатися по номерам.
rxe11=В даному регекспi не можна використовувати iменованi дужки.
rxe12=Посилання на неiснуючу пойменовану дужку.
rxe13=При реверсивному переглядi повинний бути вираз фiксованої довжини
